name:                slack-log
version:             0.1.0.0
github:              "haskell-jp/slack-log"
license:             Apache-2.0
author:              "Japan Haskell User Group"
maintainer:          "whosekiteneverfly@gmail.com"
copyright:           "2018 Japan Haskell User Group"

extra-source-files:
- README.md
- ChangeLog.md
- test/assets/*.html
- test/assets/json/id_of_random/*.json

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Development
#
description:         Please see the README on GitHub at <https://github.com/haskell-jp/slack-log#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- bytestring
- directory
- envy
- extra
- filepath
- mtl
- safe
- slack-web
- text
- time
- template-haskell
- tz
- unordered-containers
- QuickCheck
- quickcheck-instances

library:
  source-dirs: src
  dependencies:
  - type-of-html

executables:
  slack-log:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - slack-log
  paginate-old-jsons:
    main:                paginate-old-jsons.hs
    source-dirs:         app
    dependencies:
    - slack-log
  convert-old-jsons-to-htmls:
    main:                convert-old-jsons-to-htmls.hs
    source-dirs:         app
    dependencies:
    - slack-log
  devserver:
    main:                app/devserver.hs
    dependencies:
    - warp
    - wai
    - http-types
    - utf8-string

tests:
  slack-log-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - slack-log
    - hspec
