name: Verify

on:
  pull_request: null
  push:
    branches:
    - master

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019]

    steps:
    - uses: actions/checkout@v2

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v1.1.2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/package.yaml') }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - uses: mstksg/setup-stack@v2

    - name: Install dependencies
      run: stack test --only-dependencies

    - name: Run test
      run: stack test --pedantic
